name: Main CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3

      - name: .env setting
        run: |
          echo "VITE_SUPABASE_URL=${{secrets.VITE_SUPABASE_URL}}" >> .env
          echo "VITE_SUPABASE_ANON_KEY=${{secrets.VITE_SUPABASE_ANON_KEY}}" >> .env

      - name: npm install
        run: |
          npm cache clean --force
          npm install --unsafe-perm

      - name: build
        run: CI=false npm run build

      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            ./dist s3://mbti-contents-platform

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v1
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: '/*'
          AWS_REGION: 'ap-northeast-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
